booking/urls.py
from django.urls import path 
from booking import views 

app_name = "booking"

urlpatterns = [
    path("check_room_availability/", views.check_room_availability, name="check_room_availability"),
    path("delete_session/", views.delete_session, name="delete_session"),
    path("booking_data/<slug:slug>/", views.booking_data, name="booking_data"),

    # Ajax
    path("add_to_selection/", views.add_to_selection, name="add_to_selection"),
    path("delete_selection/", views.delete_selection, name="delete_selection"),
    
]

hms_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Apps Routes
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),
    path("user/", include("userauths.urls")),
    path("dashboard/", include("user_dashboard.urls")),

    # Ckeditor
    path("ckeditor5/", include('django_ckeditor_5.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path 
from hotel import views 

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    
    path("policy/", views.policy, name="policy"),
    path("tandc/", views.tandc, name="tandc"),
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
    path("services/", views.services, name="services"),
    path("rooms/", views.rooms, name="rooms"),
    path("rooms/<slug:slug>/", views.room_details, name="room_details"),
    path("blogs/", views.blogs, name="blogs"),
    path("blog/<slug:slug>", views.blog_details, name="blog_details"),
    path("detail/<slug:slug>/", views.hotel_detail, name="detail"),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
    path("checkout/<booking_id>/", views.checkout, name="checkout"),
    path("invoice/<booking_id>/", views.invoice, name="invoice"),
    path("update_room_status/", views.update_room_status, name="update_room_status"),
    
    
    # Payment API
    path('api/checkout-session/<booking_id>/', views.create_checkout_session, name='api_checkout_session'),
    path('success/<booking_id>/', views.payment_success, name='success'),
    path('failed/<booking_id>/', views.payment_failed, name='failed'),
]

hotel/views.py
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives


from hotel.models import Coupon, CouponUsers, Hotel, Room, Booking, RoomServices, HotelGallery, HotelFeatures, RoomType, Notification, Bookmark, Review, HeroSection, ManagementTeam, ServicesSection, Blogs

from datetime import datetime
from decimal import Decimal
import stripe
import json


def index(request):
    hotel = Hotel.objects.filter(status="Live")
    herosection = HeroSection.objects.all()
    room_type = RoomType.objects.all()
    blog = Blogs.objects.all()
    servicesection = ServicesSection.objects.all()
    mt = ManagementTeam.objects.all()
    try:
        reviews = Review.objects.filter(user=request.user, hotel=hotel)
    except:
        reviews = None
    all_reviews = Review.objects.filter(active=True)
    
    context = {
        "hotel":hotel,
        "herosection": herosection,
        "room": room_type,
        "blog": blog,
        "servicesection": servicesection,
        "reviews":reviews,
        "all_reviews":all_reviews,
        "management": mt
    }
    return render(request, "hotel/index.html", context)


def rooms(request):
    hotel = Hotel.objects.filter(status="Live")
    room_type = RoomType.objects.all()
    context = {
        "hotel":hotel,
        "room": room_type,
    }
    return render(request, "hotel/rooms.html", context)



def room_details(request, slug):
    hotel = Hotel.objects.filter(status="Live")
    # Use get_object_or_404 to retrieve the room_details object or return a 404 response
    room_details = get_object_or_404(RoomType, slug=slug)
    context = {
        "hotel": hotel,
        "room_details": room_details,
    }
    return render(request, "hotel/room_details.html", context)



def contact(request):
    return render(request, "hotel/contact.html")



def policy(request):
    return render(request, "hotel/policy.html")



def tandc(request):
    return render(request, "hotel/terms_and_conditions.html")



def about(request):
    hotel = Hotel.objects.filter(status="Live")
    mt = ManagementTeam.objects.all()
    context = {
        "hotel":hotel,
        "management": mt
    }
    return render(request, "hotel/about.html", context)



def services(request):
    hotel = Hotel.objects.filter(status="Live")
    servicesection = ServicesSection.objects.all()
    context = {
        "hotel":hotel,
        "servicesection": servicesection,
    }
    return render(request, "hotel/services.html", context)



def blogs(request):
    hotel = Hotel.objects.filter(status="Live")
    blog = Blogs.objects.all()
    context = {
        "hotel":hotel,
        "blog": blog,
    }
    return render(request, "hotel/blogs.html", context)



def blog_details(request, slug):
    hotel = Hotel.objects.filter(status="Live")
    # Use get_object_or_404 to retrieve the Blogs object or return a 404 response
    blog = get_object_or_404(Blogs, slug=slug)
    context = {
        "hotel": hotel,
        "blog": blog,
    }
    return render(request, "hotel/blog_details.html", context)



def hotel_detail(request, slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)
    try:
        reviews = Review.objects.filter(user=request.user, hotel=hotel)
    except:
        reviews = None
    all_reviews = Review.objects.filter(hotel=hotel, active=True)
    
    if request.user.is_authenticated:
        bookmark = Bookmark.objects.filter(user=request.user, hotel=hotel)
    else:
        bookmark = None
    context = {
        "hotel":hotel,
        "bookmark":bookmark,
        "reviews":reviews,
        "all_reviews":all_reviews,
    }
    return render(request, "hotel/hotel_detail.html", context)



def room_type_detail(request, slug, rt_slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)
    room_type = RoomType.objects.get(hotel=hotel, slug=rt_slug)
    rooms = Room.objects.filter(room_type=room_type, is_available=True)

    id = request.GET.get("hotel-id")
    checkin = request.GET.get("checkin")
    checkout = request.GET.get("checkout")
    adult = request.GET.get("adult")
    children = request.GET.get("children")
    room_type_ = request.GET.get("room-type")

    print("checkin ======", checkin)

    if not all([checkin, checkout]):
        messages.warning(request, "Please enter your booking data to check availability.")
        return redirect("booking:booking_data", hotel.slug)

    context = {
        "hotel":hotel,
        "room_type":room_type,
        "rooms":rooms,
        "id":id,
        "checkin":checkin,
        "checkout":checkout,
        "adult":adult,
        "children":children,
        "room_type_":room_type_,
    }
    return render(request, "hotel/room_type_detail.html", context)



def selected_rooms(request):
    # request.session.pop('selection_data_obj', None)

    total = 0
    room_count = 0
    total_days = 0
    adult = 0 
    children = 0 
    checkin = "0" 
    checkout = "" 
    children = 0 
    
    if 'selection_data_obj' in request.session:

        if request.method == "POST":
            for h_id, item in request.session['selection_data_obj'].items():
                
                id = int(item['hotel_id'])
                hotel_id = int(item['hotel_id'])

                checkin = item["checkin"]
                checkout = item["checkout"]
                adult = int(item["adult"])
                children = int(item["children"])
                room_type_ = item["room_type"]
                room_id = int(item["room_id"])
                
                user = request.user
                hotel = Hotel.objects.get(id=id)
                room = Room.objects.get(id=room_id)
                room_type = RoomType.objects.get(id=room_type_)

                

                
            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            full_name = request.POST.get("full_name")
            email = request.POST.get("email")
            phone = request.POST.get("phone")

            booking = Booking.objects.create(
                hotel=hotel,
                room_type=room_type,
                check_in_date=checkin,
                check_out_date=checkout,
                total_days=total_days,
                num_adults=adult,
                num_children=children,
                full_name=full_name,
                email=email,
                phone=phone
            )

            if request.user.is_authenticated:
                booking.user = request.user
                booking.save()
            else:
                booking.user = None
                booking.save()


            for h_id, item in request.session['selection_data_obj'].items():
                room_id = int(item["room_id"])
                room = Room.objects.get(id=room_id)
                booking.room.add(room)

                room_count += 1
                days = booking.total_days
                price = booking.room_type.price

                room_price = price * room_count
                total = room_price * days

                # print("room_price ==",room_price)
                # print("total ==",total)
            
            booking.total += float(total)
            booking.before_discount += float(total)
            booking.save()

            messages.success(request, "Checkout Now!")
            return redirect("hotel:checkout", booking.booking_id)

        hotel = None

        for h_id, item in request.session['selection_data_obj'].items():
                
            id = int(item['hotel_id'])
            hotel_id = int(item['hotel_id'])

            checkin = item["checkin"]
            checkout = item["checkout"]
            adult = int(item["adult"])
            children = int(item["children"])
            room_type_ = item["room_type"]
            room_id = int(item["room_id"])
            
            room_type = RoomType.objects.get(id=room_type_)

            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            room_count += 1
            days = total_days
            price = room_type.price

            room_price = price * room_count
            total = room_price * days
            
            hotel = Hotel.objects.get(id=id)

        print("hotel ===", hotel)
        context = {
            "data":request.session['selection_data_obj'], 
            "total_selected_items": len(request.session['selection_data_obj']),
            "total":total,
            "total_days":total_days,
            "adult":adult,
            "children":children,   
            "checkin":checkin,   
            "checkout":checkout,   
            "hotel":hotel,   
        }

        return render(request, "hotel/selected_rooms.html", context)
    else:
        messages.warning(request, "You don't have any room selections yet!")
        return redirect("/")



def checkout(request, booking_id):
    booking = Booking.objects.get(booking_id=booking_id)
    hotel = Hotel.objects.get(status="Live")

    if booking.payment_status == "paid":
        messages.success(request, "This order has been paid for!")
        return redirect("/")
    else:
        booking.payment_status = "processing"
        booking.save()


    # Coupon

templates/hotel/blog_details.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}


    <!-- the hero section and slider starts here  -->
    <section class="about-hero py-5" style="background: linear-gradient(rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.65)), url('{% static 'images/bg_29.jpg' %}'); background-repeat: no-repeat; background-position: center; background-size: cover; background-attachment: fixed;">
        <div class="contianer py-5">
            <div class="row py-5">
                <div class="col-10 mx-auto text-light w-50 text-center py-5">
                    <h1 class="fw-bolder fs-1 text-light" style="font-weight: 900;">Blog Posts</h1>
                    <p><a href="{% url 'hotel:index' %}" style="text-decoration: none;"><span class="span-color">Home</span></a> / <a href="{% url 'hotel:blogs' %}" style="text-decoration: none;"><span class="span-color">Blogs</span></a> / Blog Details</p>
                </div>
            </div>
        </div>
    </section>
    <!-- the hero section and slider stops here  -->

    <!-- main blog details section starts here -->
<div class="container py-5">
    <div class="row py-5 justify-content-center">
        <div class="col-8">
            <img src="{{ blog.image1.url }}" class="img img-fluid" alt="{{ item.slug }}">
            <div class="row justify-content-evenly">
                <p class="col-6">Posted by: <strong class="span-color">{{ blog.user }}</strong></p>
                <p class="col-6 text-center text-primary">{{ blog.date|date:"d M, Y" }}</p>
            </div>
        </div>
        <div class="col-8 py-5">
            <p style="text-align: justify !important;">{{ blog.details|safe }}</p>
        </div>
    </div>
</div>

    <!-- main blog details section stops here -->
{% endblock content %}

templates/hotel/blogs.html
{% extends 'partials/base.html' %}
{% load static %}
{% block page_seo %}
    <meta name="description" content="Stay informed and inspired with the latest updates from Liberation Suite Hotel's blog. Discover travel tips, local insights, and everything you need to make your stay with us even more extraordinary.">
    <meta name='robots' content='index, follow'>
{% endblock %}

<title>{% block title %} Explore Our Blog - Liberation Suite Hotel, Gwarinpa {% endblock %}</title>
{% block content %}


    <!-- the hero section and slider starts here  -->
    <section class="about-hero py-5" style="background: linear-gradient(rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.65)), url('{% static 'images/Liberation-Suite-Hotel-rv3.jpg' %}'); background-repeat: no-repeat; background-position: center; background-size: cover; background-attachment: fixed;">
        <div class="contianer py-5">
            <div class="row py-5">
                <div class="col-10 mx-auto text-light w-50 text-center py-5">
                    <h1 class="fw-bolder fs-1 text-light" style="font-weight: 900;">Blog Posts</h1>
                    <p><a href="{% url 'hotel:index' %}" style="text-decoration: none;"><span class="span-color">Home</span></a> / Blogs</p>
                </div>
            </div>
        </div>
    </section>
    <!-- the hero section and slider stops here  -->

    <section class="fullwidth_block padding-top-75 padding-bottom-75" data-background-color="#ffffff">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="headline_part centered margin-bottom-50"> Letest Tips & Blog<span>Discover & connect with top-rated local businesses</span></h3>
                </div>
            </div>
            <div class="row">
                {% for item in blog %}
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <a href="{% url 'hotel:blog_details' item.slug %}" class="blog_compact_part-container">
                        <div class="blog_compact_part"> <img src="{{ item.image1.url }}" alt="">
                            <div class="blog_compact_part_content">
                                <h3>{{ item.title }}</h3>
                                <ul class="blog_post_tag_part">
                                    <li>{{ item.date }}</li>
                                </ul>
                                <!-- <p class="text-light">{{ item.details|safe|slice:":150" }}... </p> -->
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock content %}

templates/hotel/payment_failed.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  
  <div class="not_found_block">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <section id="not-found" class="center">
            <h2 class="margin-bottom-10"><i class="fas fa-times-circle" style="color: red;"></i></h2>
            <p style="margin-top: 10px; color: black;"><b>Payment Unsuccessful</b></p>
            <div class="utf_error_description_part utf_ferror_description">  
                <span class="f-primary animated v fadeInRight">There was an issue processing your payment. Please try again or contact support.</span> 
            </div>
            <a href="{% url 'hotel:index' %}" class="button margin-top-20">Go to Home</a>
            <div class="row">
              <div class="col-lg-6 col-lg-offset-3">
                <div class="gray-style margin-top-50 margin-bottom-10">
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/hotel/rooms.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}


    <!-- the hero section and slider starts here  -->
    <section class="about-hero py-5" style="background: linear-gradient(rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.65)), url('{% static 'images/Liberation-Suite-Hotel-rv3.jpg' %}'); background-repeat: no-repeat; background-position: center; background-size: cover; background-attachment: fixed;">
        <div class="contianer py-5">
            <div class="row py-5">
                <div class="col-10 mx-auto text-light w-50 text-center py-5">
                    <h1 class="fw-bolder fs-1 text-light" style="font-weight: 900;">Rooms Page</h1>
                    <p><a href="{% url 'hotel:index' %}" style="text-decoration: none;"><span class="span-color">Home</span></a> / Rooms</p>
                </div>
            </div>
        </div>
    </section>
    <!-- the hero section and slider stops here  -->

    <section class="fullwidth_block padding-top-75 padding-bottom-75" data-background-color="#ffffff">
        <div class="container">
            <div class="intro mb-5 text-center">
                <h2 class="fw-bolder headline_part">Our Exquisite <strong class="span-color">Rooms</strong></h2>
                <p class="mx-auto" style="width: 80%;">Step into a world of refined elegance and unparalleled comfort. Our exquisite rooms are meticulously designed to elevate your stay, ensuring a truly luxurious and memorable experience.</p>
            </div>
            <div class="row justify-content-center">
                {% for item in room %}
                <div class="col-md-10 col-12 my-3 mx-3">
                    <div class="card p-2 shadow-lg">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <div class="carousel slide" id="carouselExample{{ item.carousel_number }}" data-bs-ride="carousel">
                                    <div class="carousel-inner" style="height: max-content;">
                                        
                                        <div class="carousel-item active" >
                                            <span class="badge text-bg-danger m-1 position-absolute top-0 start-0" style="border-radius: 0px 15px; padding: 7.5px 15px; font-size: 1rem;">New</span>
                                            <img src="{{ item.image1.url }}" alt="liberation-suite-hotel-{{item.slug}}" class="d-block w-100 h-100 img-fluid rounded">
                                        </div>
                                        <div class="carousel-item">
                                            <span class="badge text-bg-danger m-1 position-absolute top-0 start-0" style="border-radius: 0px 15px; padding: 7.5px 15px; font-size: 1rem;">New</span>
                                            <img src="{{ item.image2.url }}" alt="liberation-suite-hotel-{{item.slug}}" class="d-block w-100 h-100 img-fluid rounded">
                                        </div>
                                        <div class="carousel-item">
                                            <span class="badge text-bg-danger m-1 position-absolute top-0 start-0" style="border-radius: 0px 15px; padding: 7.5px 15px; font-size: 1rem;">New</span>
                                            <img src="{{ item.image3.url }}" alt="liberation-suite-hotel-{{item.slug}}" class="d-block w-100 h-100 img-fluid rounded">
                                        </div>
                                        <div class="carousel-item">
                                            <span class="badge text-bg-danger m-1 position-absolute top-0 start-0" style="border-radius: 0px 15px; padding: 7.5px 15px; font-size: 1rem;">New</span>
                                            <img src="{{ item.image4.url }}" alt="liberation-suite-hotel-{{item.slug}}" class="d-block w-100 h-100 img-fluid rounded">
                                        </div>
                                        <!-- <div class="carousel-item">
                                            <span class="badge text-bg-danger m-1 position-absolute top-0 start-0" style="border-radius: 0px 15px; padding: 7.5px 15px; font-size: 1rem;">New</span>
                                            <img src="{{ item.image3.url }}" alt="Third Slide" class="d-block w-100 h-100 img-fluid rounded">
                                        </div> -->
                                    </div>
                                    <a href="#carouselExample{{ item.carousel_number }}" class="carousel-control-prev" data-bs-target="#carouselExample{{ item.carousel_number }}" data-bs-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a href="#carouselExample{{ item.carousel_number }}" class="carousel-control-next" data-bs-target="#carouselExample{{ item.carousel_number }}" data-bs-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
        
                                    <div class="m-2 p-2 c4 text-dark" style="border-radius: 20px;">
                                        <div class="row text-center fs-4">
                                            <div class="col-4">
                                                <i class="fa-solid fa-bed"></i>
                                                <span>{{ item.number_of_beds }}</span>
                                            </div>
                                            <div class="col-4">
                                                <i class="fa-solid fa-person"></i>
                                                <span>{{ item.room_capacity }}</span>
                                            </div>
                                            <div class="col-4">
                                                <i class="fa-solid fa-maximize"></i>
                                                <span>{{ item.room_size }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card-body">
                                    <div class="row mt-3 mb-3 justify-content-evenly">
                                        <div class="col-7">
                                            <h5 class="card-title fw-bolder my-3 fs-3 ms-4" style="font-size: 2rem !important;">{{ item.type }}</h5>
                                        </div>
                                        <div class="col-5">
                                            <p class="fs-5 fw-bolder my-3"><span class="fs-3 span-color fw-bolder">₦ {{ item.price }}</span> Per day</p>
                                        </div>                                    
                                    </div>
                                    <a href="{% url 'hotel:room_details' item.slug %}" class="text-decoration-none text-dark"><p class="card-text px-3" style="text-align: justify;">{{ item.description|slice:":150"|safe}}...</p></a>
                                    <div class="row mt-3 mb-3 justify-content-between">
                                        <div class="col-5">
                                            <a href="{% url 'hotel:room_details' slug=item.slug %}" class="btn contrast-custom-btn py-2" style="border-radius: 10px;">More Details</a>
                                        </div>
                                        <div class="col-5">
                                            {% for h in hotel %}
                                            <a href="{% url 'hotel:detail' h.slug %}#bkg" class="btn contrast-custom-btn py-2" style="border-radius: 10px; float: inline-end;"><i class="fa-regular fa-bookmark mr-4"></i> Book Now</a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div> 
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock content %}

templates/hotel/services.html
{% extends 'partials/base.html' %}
{% load static %}

{% block page_seo %}
    <meta name="description" content="Explore our range of meticulously crafted rooms and premium amenities at Liberation Suite Hotel, Gwarinpa. From opulent Supreme Rooms to versatile Standard Suites, we offer a perfect blend of comfort and style.">
    <meta name='robots' content='index, follow'>
{% endblock %}

<title>{% block title %} Premium Services at Liberation Suite Hotel, Gwarinpa {% endblock %}</title>
<!-- the hero section and slider starts here  -->
{% block content %} 
    <section class="about-hero py-5" style="background: linear-gradient(rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.65)), url('{% static 'images/Liberation-Suite-Hotel-kv1.jpg' %}'); background-repeat: no-repeat; background-position: bottom; background-size: cover; background-attachment: fixed;">
        <div class="contianer py-5">
            <div class="row py-5">
                <div class="col-10 mx-auto text-light w-50 text-center py-5">
                    <h1 class="fw-bolder headline_part text-light">Services</h1>
                    <p><a href="{% url 'hotel:index' %}" style="text-decoration: none;"><span class="span-color">Home</span></a> / Services</p>
                </div>
            </div>
        </div>
    </section>
        
<!-- the hero section and slider stops here  -->

 <!-- Body section starts here  -->
    <!-- Services offered starts here  -->
    <div id="service"></div>
    <section class="s-two c2 py-5">
        <div class="container mt-5 mb-5">
            <div class="intro text-center mb-5">
                <h2 class="fw-bolde headline_part">Our Amazing <strong class="span-color">Facilities</strong></h2>
                <p class="m-0 mx-auto" style="width: 80%;">At Liberation Suite, we are dedicated to providing a unique and unforgettable experience for our guests. Our range of services is designed to ensure comfort, convenience, and an unparalleled stay. Explore the exceptional services we offer:</p>
            </div>
            <div class="row text-dark justify-content-center">
                {% for item in servicesection %}
                <div class="col-md-10 col-12 my-3">
                    <div class="card py-3 shadow-lg" style="border-radius: 10px;">
                        <div class="row justify-content-center">
                            <div class="col-md-4 my-auto">
                                <img src="{{ item.image.url }}" class="img img-fluid" alt="liberation-suite-hotel{{ item.slug }}">
                            </div>
                            <div class="col-md-7 my-auto">
                                <div class="card-body">
                                    <h5 class="card-title fw-bolder fs-2 my-3"><i class="fa-solid {{ item.icon }} me-3 span-color"></i>{{ item.title }}</h5>
                                    <p class="card-text pt-2 lh-lg">{{ item.text }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% for h in hotel %}
            <blockquote class="my-5 text-justify">
                At Liberation Suite, we go beyond accommodation to create a haven where every detail is carefully curated for your comfort. Explore our services and let us redefine your expectations of hospitality. Your satisfaction is our commitment.

                <a href="{% url 'hotel:detail' h.slug %}#bkg" class="span-color">Book</a> your stay at Liberation Suite today and discover a world of refined services and warm hospitality. Welcome to a place where every moment is designed to make your stay truly exceptional.
            </blockquote>
            {% endfor %}
        </div>
    </section>
    <!-- Services offered stops here  -->
 {% endblock content %}
 <!-- Body section stops here  -->